### PR TITLE
Create symlinks for Python major version to install path

### PR DESCRIPTION
**Pull request by MrTango**

### CODE REVIEW

**Comment by gforcada** [comment]
Thanks for your contribution!

I see the point but at the same time I would prefer to make it as much explicit as it can be.

We could create a symlink maybe?

My biggest fear is that depending on what you are doing you may want to have more than one version installed, the one that is already installed and the new one that you are upgrading to. In those occasions, you don't want to accidentally update virtualenvs or other depending scripts to a newer version without carefully checking for it.

**Comment by MrTango** [comment]
I don't have the need, but i see your point.
Symlink could work too.
But on the other hand, if you now update the versions in the default and someone updates the role, he also get a new version, but in a different path. Or do we keep the old versions? And we keepthe old versions, how should we cleanup this after sometime?

**Comment by MrTango** [comment]
I changed it to creating symlinks for the python major versions

**Comment by gforcada** [comment]
Yeah you got a point there (updating the symlink breaks anyway), then I would rather keep the symlink but create it only once.

I wouldn't rely on that symlink for virtualenvs or long running tasks, but for the small throw away utilities/scripts that wouldn't be a problem.

Would that be ok with you?

**Comment by MrTango** [comment]
Updating the symlink works, i have tested that. When you switch to a new version and run the playbook again, you will have the symlink to the new version.
For virtualenv it isn't actually a Problem if something changed, because they make a hard copy of the binary.
Should work even if we change the symlink afterwards.
BTW I also did a pull request on ansible.plone_server to allow using custom Python path ;)

**Comment by gforcada** [comment]
Ok great, then let's have it in :-)

Thanks!

**Comment by gforcada** [comment]
@MrTango 1.1.0 tagged

**Pull request merged**
