### PR TITLE
Basic changes for python 2.4.

### PR DESCRIPTION
**Pull request by fulv**
DO NOT MERGE
Just FYI for #1

### CODE REVIEW

**Comment by fulv** [comment]
Actually, this could be merged now, as far as I'm concerned.

**Comment by gforcada** [comment]
@fulv would you mind rebasing? I merged the zlib changes for 2.6

I was thinking about having different virtualenv's per python (just like you did  here, neat!) but so far it didn't work... have you tried this virtualenv version that you use for python 2.4 for python2.6?

**Comment by fulv** [comment]
@gforcada I tried the virtualenv for python 2.4 and it worked.  The one for 2.6 failed with the error in https://github.com/gforcada/ansible-compile-python/issues/2#issuecomment-224780952.

Will rebase.

**Comment by gforcada** [comment]
@fulv I just tried to use virtualenv 1.7 for python 2.6 and it works :-) I will try to update it to a not so old version...

**Comment by gforcada** [comment]
I just manually merged the code and squashed it into a single commit, plus some minor fixes.

Thanks a lot!

**Pull request closed without merging**
